# Generated by Django 5.1.3 on 2024-11-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('individual_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'individuals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccinationhistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccination_date', models.DateField(blank=True, null=True)),
                ('vaccination_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'vaccinationhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccinationtypes',
            fields=[
                ('vaccination_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccination_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vaccinationtypes',
                'managed': False,
            },
        ),
    ]
